#!/usr/bin/env  python
import rospy
from std_msgs.msg import Float64
from geometry_msgs.msg import Vector3


from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PlatformController(object):
    def setupUi(self, PlatformController):
        PlatformController.setObjectName(_fromUtf8("PlatformController"))
        PlatformController.setEnabled(True)
        PlatformController.resize(690, 532)
        PlatformController.setWindowTitle(_fromUtf8(""))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.dial_lf = QtGui.QDial(self.dockWidgetContents)
        self.dial_lf.setGeometry(QtCore.QRect(390, 150, 180, 180))
        self.dial_lf.setMinimum(-90)
        self.dial_lf.setMaximum(90)
        self.dial_lf.setSingleStep(1)
        self.dial_lf.setObjectName(_fromUtf8("dial_lf"))
        self.dial_ri = QtGui.QDial(self.dockWidgetContents)
        self.dial_ri.setGeometry(QtCore.QRect(130, 150, 180, 180))
        self.dial_ri.setMinimum(-90)
        self.dial_ri.setMaximum(90)
        self.dial_ri.setSingleStep(1)
        self.dial_ri.setObjectName(_fromUtf8("dial_ri"))
        self.widget = QtGui.QWidget(self.dockWidgetContents)
        self.widget.setGeometry(QtCore.QRect(230, 10, 231, 121))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_7 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setLineWidth(2)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLineWidth(2)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.label_ri_val_read = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_ri_val_read.setFont(font)
        self.label_ri_val_read.setMouseTracking(False)
        self.label_ri_val_read.setAcceptDrops(True)
        self.label_ri_val_read.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_ri_val_read.setLineWidth(2)
        self.label_ri_val_read.setText(_fromUtf8(""))
        self.label_ri_val_read.setTextFormat(QtCore.Qt.AutoText)
        self.label_ri_val_read.setObjectName(_fromUtf8("label_ri_val_read"))
        self.horizontalLayout.addWidget(self.label_ri_val_read)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLineWidth(2)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_lf_val_read = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_lf_val_read.setFont(font)
        self.label_lf_val_read.setMouseTracking(False)
        self.label_lf_val_read.setAcceptDrops(True)
        self.label_lf_val_read.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_lf_val_read.setLineWidth(2)
        self.label_lf_val_read.setText(_fromUtf8(""))
        self.label_lf_val_read.setTextFormat(QtCore.Qt.AutoText)
        self.label_lf_val_read.setObjectName(_fromUtf8("label_lf_val_read"))
        self.horizontalLayout_2.addWidget(self.label_lf_val_read)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_6.setLineWidth(2)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label_baseline_val_read = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_baseline_val_read.setFont(font)
        self.label_baseline_val_read.setMouseTracking(False)
        self.label_baseline_val_read.setAcceptDrops(True)
        self.label_baseline_val_read.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_baseline_val_read.setLineWidth(2)
        self.label_baseline_val_read.setText(_fromUtf8(""))
        self.label_baseline_val_read.setTextFormat(QtCore.Qt.AutoText)
        self.label_baseline_val_read.setObjectName(_fromUtf8("label_baseline_val_read"))
        self.horizontalLayout_3.addWidget(self.label_baseline_val_read)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.widget1 = QtGui.QWidget(self.dockWidgetContents)
        self.widget1.setGeometry(QtCore.QRect(130, 340, 161, 51))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLineWidth(2)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label_ri_val = QtGui.QLabel(self.widget1)
        self.label_ri_val.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_ri_val.setFont(font)
        self.label_ri_val.setMouseTracking(False)
        self.label_ri_val.setAcceptDrops(True)
        self.label_ri_val.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_ri_val.setLineWidth(2)
        self.label_ri_val.setText(_fromUtf8(""))
        self.label_ri_val.setTextFormat(QtCore.Qt.AutoText)
        self.label_ri_val.setObjectName(_fromUtf8("label_ri_val"))
        self.horizontalLayout_4.addWidget(self.label_ri_val)
        self.widget2 = QtGui.QWidget(self.dockWidgetContents)
        self.widget2.setGeometry(QtCore.QRect(90, 440, 521, 51))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLineWidth(2)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_6.addWidget(self.label)
        self.hs_baseline = QtGui.QSlider(self.widget2)
        self.hs_baseline.setMinimum(50)
        self.hs_baseline.setMaximum(520)
        self.hs_baseline.setOrientation(QtCore.Qt.Horizontal)
        self.hs_baseline.setObjectName(_fromUtf8("hs_baseline"))
        self.horizontalLayout_6.addWidget(self.hs_baseline)
        self.label_baseline_val = QtGui.QLabel(self.widget2)
        self.label_baseline_val.setEnabled(False)
        self.label_baseline_val.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_baseline_val.setFont(font)
        self.label_baseline_val.setMouseTracking(False)
        self.label_baseline_val.setAcceptDrops(True)
        self.label_baseline_val.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_baseline_val.setLineWidth(2)
        self.label_baseline_val.setText(_fromUtf8(""))
        self.label_baseline_val.setTextFormat(QtCore.Qt.AutoText)
        self.label_baseline_val.setObjectName(_fromUtf8("label_baseline_val"))
        self.horizontalLayout_6.addWidget(self.label_baseline_val)
        self.widget3 = QtGui.QWidget(self.dockWidgetContents)
        self.widget3.setGeometry(QtCore.QRect(400, 340, 161, 52))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLineWidth(2)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.label_lf_val = QtGui.QLabel(self.widget3)
        self.label_lf_val.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_lf_val.setFont(font)
        self.label_lf_val.setMouseTracking(False)
        self.label_lf_val.setAcceptDrops(True)
        self.label_lf_val.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_lf_val.setLineWidth(2)
        self.label_lf_val.setTextFormat(QtCore.Qt.AutoText)
        self.label_lf_val.setObjectName(_fromUtf8("label_lf_val"))
        self.horizontalLayout_5.addWidget(self.label_lf_val)
        self.dial_lf.raise_()
        self.dial_ri.raise_()
        self.hs_baseline.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_lf_val.raise_()
        self.label_ri_val.raise_()
        self.label_4.raise_()
        self.label_lf_val_read.raise_()
        self.label_ri_val_read.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_baseline_val_read.raise_()
        self.label_7.raise_()
        self.label_baseline_val.raise_()
        self.label_7.raise_()
        
        PlatformController.setWidget(self.dockWidgetContents)

        self.retranslateUi(PlatformController)
        QtCore.QMetaObject.connectSlotsByName(PlatformController)

        ###############################
        self.update_gui()
        self.baseline_sub = rospy.Subscriber('/baseline/position', Float64, self.baseline_callback)
        self.left_sub = rospy.Subscriber('/left/pan/angle', Float64, self.left_callback)
        self.right_sub = rospy.Subscriber('/right/pan/angle', Float64, self.right_callback)

        self.baseline_pub = rospy.Publisher('/baseline/move', Float64, queue_size=10)
        self.left_angle_pub = rospy.Publisher('/left/pan/move', Vector3, queue_size=10)
        self.right_angle_pub = rospy.Publisher('/right/pan/move', Vector3, queue_size=10)


    def baseline_callback(self,msg):
        val = str('%.2f'%(msg.data))
        self.label_baseline_val_read.setText(val) 

    def left_callback(self,msg):
        val = str('%.2f'%(msg.data))
        self.label_lf_val_read.setText(val)

    def right_callback(self,msg):
        val = str('%.2f'%(msg.data))
        self.label_ri_val_read.setText(val)

    '''
    the update code 
    '''
    def update_gui(self):
        self.hs_baseline.valueChanged.connect(self.update_baseline)
        self.dial_lf.valueChanged.connect(self.update_left)
        self.dial_ri.valueChanged.connect(self.update_right)


    # Define the update methods for the gui 
    def update_baseline(self):
        val = self.hs_baseline.value()
        self.label_baseline_val.setText(str(val))
        self.baseline_pub.publish(val)

    def update_left(self):
        val = str(self.dial_lf.value())
        self.label_lf_val.setText(val)
        angle = Vector3()
        angle.x = self.dial_lf.value()
        angle.y = 0
        angle.z = 0
        self.left_angle_pub.publish(angle)


    def update_right(self):
        val = str(self.dial_ri.value())
        self.label_ri_val.setText(val)
        angle = Vector3()
        angle.x = self.dial_ri.value()
        angle.y = 0
        angle.z = 0
        self.right_angle_pub.publish(angle)


    def retranslateUi(self, PlatformController):
        self.label_7.setText(_translate("PlatformController", "Encoder Reading", None))
        self.label_5.setText(_translate("PlatformController", "Right :", None))
        self.label_4.setText(_translate("PlatformController", "Left :", None))
        self.label_6.setText(_translate("PlatformController", "Baseline :", None))
        self.label_2.setText(_translate("PlatformController", "Right :", None))
        self.label.setText(_translate("PlatformController", "Baseline", None))
        self.label_3.setText(_translate("PlatformController", "Left :", None))
        self.label_lf_val.setText(_translate("PlatformController", " ", None))


if __name__ == "__main__":
    import sys
    rospy.init_node('follower')
    app = QtGui.QApplication(sys.argv)
    PlatformController = QtGui.QDockWidget()
    ui = Ui_PlatformController()
    ui.setupUi(PlatformController)
    PlatformController.show()
    sys.exit(app.exec_())

